package yate.view;

import java.awt.Font;
import javax.swing.text.StyledDocument;
import yate.listener.CenterBox.DocumentUpdateAction;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Laurin
 */
public class CenterBoxView extends javax.swing.JPanel {

    /**
     * Creates new form CenterBox
     */
    public CenterBoxView() {
        initComponents();
        TextLineNumberComponent tln = new TextLineNumberComponent(jTP_text);
        tln.setUpdateFont(true);
        jScrollPane1.setRowHeaderView(tln);
    }

    public StyledDocument getStyledDocument() {
        return this.jTP_text.getStyledDocument();
    }

    public void setFont(String font, int size) {
        jTP_text.setFont(new Font(font, 0, size));
    }

    public void addDocumentUpdateAction(DocumentUpdateAction l) {
        jTP_text.getDocument().addDocumentListener(l);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTP_text = new javax.swing.JTextPane();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setViewportView(jTP_text);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTP_text;
    // End of variables declaration//GEN-END:variables


    /* @Override
     public JComponent getComponent(String Name) {
     return components.get(Name);
     }*/
}
