package yate.view;

import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import javax.swing.event.ChangeListener;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Laurin
 */
public class ChangeColorDialog extends javax.swing.JDialog {

    /**
     * Creates new form ChangeColorDialog
     *
     * @param parent
     */
    public ChangeColorDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        this.setLocationRelativeTo(parent);
        jL_list.setCellRenderer(new SimpleCellRenderer());
        jCC_colorChooser.setPreviewPanel(new JPanel());
    }

    public Color getChosenColor() {
        return jCC_colorChooser.getColor();
    }

    public void repaintList() {
        jL_list.repaint();
    }

    public void setChoserColor(Color c) {
        jCC_colorChooser.setColor(c);
    }

    public int getSelectedIndex() {
        return jL_list.getSelectedIndex();
    }

    public void setDefaultListModel(DefaultListModel dlm) {
        jL_list.setModel(dlm);
        if (dlm != null && dlm.size() > 0) {
            jL_list.setSelectedIndex(0);
        }
    }

    //Listener
    public void addCancelButtonListener(ActionListener l) {
        jB_cancel.addActionListener(l);
    }

    public void addConfirmButtonListener(ActionListener l) {
        jB_oK.addActionListener(l);
    }

    public void addSelectedItemChangedListener(ListSelectionListener l) {
        jL_list.addListSelectionListener(l);
    }

    public void addColorChangedListener(ChangeListener l) {
        jCC_colorChooser.getSelectionModel().addChangeListener(l);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jB_oK = new javax.swing.JButton();
        jB_cancel = new javax.swing.JButton();
        jCC_colorChooser = new javax.swing.JColorChooser();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jL_list = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Farben Bearbeiten");
        setModal(true);

        jB_oK.setText("OK");
        jPanel1.add(jB_oK);

        jB_cancel.setText("Abbrechen");
        jPanel1.add(jB_cancel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(jCC_colorChooser, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(130, 131));

        jScrollPane1.setViewportView(jL_list);

        jPanel2.add(jScrollPane1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_cancel;
    private javax.swing.JButton jB_oK;
    private javax.swing.JColorChooser jCC_colorChooser;
    private javax.swing.JList jL_list;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
