/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yate.view;

import java.util.ArrayList;
import javax.swing.text.Document;
import yate.controll.CenterBoxController;
import yate.model.CenterBoxModel;

/**
 *
 * @author Laurin
 */
public class MainFrameView extends javax.swing.JFrame {

    ArrayList<CenterBoxController> cbController;

    /**
     * Creates new form MainFrame
     */
    public MainFrameView() {

        initComponents();

        cbController = new ArrayList<>();

        //Zum debuggen
        addCenterBox("Datei 1");
        addCenterBox("Datei 2");
        addCenterBox("Datei 3");
    }

    public void addCenterBox(String fileName) {
        CenterBoxView view = new CenterBoxView();
        Document d = view.getEditorPaneDocument();
        CenterBoxModel model = new CenterBoxModel(d);

        CenterBoxController cbc = new CenterBoxController(view, model);
        cbc.addListener();

        cbController.add(cbc);

        jTabbedPane1.addTab(fileName, view);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMenu = new javax.swing.JPanel();
        jPSide = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        sideMenuView1 = new yate.view.SideMenuView();
        jPBottom = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPMenu.setLayout(new javax.swing.BoxLayout(jPMenu, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(jPMenu, java.awt.BorderLayout.PAGE_START);

        jPSide.setLayout(new javax.swing.BoxLayout(jPSide, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(sideMenuView1);

        jScrollPane1.setViewportView(jPanel1);

        jPSide.add(jScrollPane1);

        getContentPane().add(jPSide, java.awt.BorderLayout.LINE_START);

        jPBottom.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPBottom.setMinimumSize(new java.awt.Dimension(0, 30));
        jPBottom.setPreferredSize(new java.awt.Dimension(603, 30));

        javax.swing.GroupLayout jPBottomLayout = new javax.swing.GroupLayout(jPBottom);
        jPBottom.setLayout(jPBottomLayout);
        jPBottomLayout.setHorizontalGroup(
            jPBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );
        jPBottomLayout.setVerticalGroup(
            jPBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPBottom, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPBottom;
    private javax.swing.JPanel jPMenu;
    private javax.swing.JPanel jPSide;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private yate.view.SideMenuView sideMenuView1;
    // End of variables declaration//GEN-END:variables
}
