package yate.view;

import java.util.HashMap;
import javax.swing.JComponent;

/**
 *
 * @author Laurin
 */
public class MainFrameView extends javax.swing.JFrame implements View {

    private HashMap<String, JComponent> components;

    /**
     * Creates new form MainFrame
     */
    public MainFrameView() {

        initComponents();

        components = new HashMap<>();
        addComponentsToHashMap();

    }

    private void addComponentsToHashMap() {
        components.put("jMI_editColors", jMI_editColors);
        components.put("jB_next", jB_next);
        components.put("jbCB_regex", jbCB_regex);
        components.put("jCB_font", jCB_font);
        components.put("jMI_open", jMI_open);
        components.put("jMI_new", jMI_new);
        components.put("jCB_fontSize", jCB_fontSize);
        components.put("jB_saveAll", jB_saveAll);
        components.put("jMI_languageSub", jMI_languageSub);
        components.put("jP_Side", jP_Side);
        components.put("jTF_search", jTF_search);
        components.put("jM_edit", jM_edit);
        components.put("jLabel2", jLabel2);
        components.put("jMI_saveAll", jMI_saveAll);
        components.put("jLabel1", jLabel1);
        components.put("jB_replaceAll", jB_replaceAll);
        components.put("jTF_replace", jTF_replace);
        components.put("jScrollPane1", jScrollPane1);
        components.put("jB_newFile", jB_newFile);
        components.put("jP_Menu", jP_Menu);
        components.put("jB_open", jB_open);
        components.put("jB_save", jB_save);
        components.put("jP_Pmv", jP_Pmv);
        components.put("jP_search", jP_search);
        components.put("jB_previous", jB_previous);
        components.put("jB_replace", jB_replace);
        components.put("jMB_menuBar", jMB_menuBar);
        components.put("jM_file", jM_file);
        components.put("jP_Center", jP_Center);
        components.put("jP_searchContainer", jP_searchContainer);
        components.put("jMI_save", jMI_save);
        components.put("jTP_tabed", jTP_tabed);

    }

    @Override
    public JComponent getComponent(String Name) {
        return components.get(Name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jP_Menu = new javax.swing.JPanel();
        jB_newFile = new javax.swing.JButton();
        jB_open = new javax.swing.JButton();
        jB_save = new javax.swing.JButton();
        jB_saveAll = new javax.swing.JButton();
        jCB_font = new javax.swing.JComboBox();
        jCB_fontSize = new javax.swing.JComboBox();
        jP_Side = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jP_Pmv = new javax.swing.JPanel();
        jP_Center = new javax.swing.JPanel();
        jTP_tabed = new javax.swing.JTabbedPane();
        jP_searchContainer = new javax.swing.JPanel();
        jP_search = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTF_search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTF_replace = new javax.swing.JTextField();
        jB_next = new javax.swing.JButton();
        jB_previous = new javax.swing.JButton();
        jB_replace = new javax.swing.JButton();
        jB_replaceAll = new javax.swing.JButton();
        jbCB_regex = new javax.swing.JCheckBox();
        jMB_menuBar = new javax.swing.JMenuBar();
        jM_file = new javax.swing.JMenu();
        jMI_new = new javax.swing.JMenuItem();
        jMI_open = new javax.swing.JMenuItem();
        jMI_save = new javax.swing.JMenuItem();
        jMI_saveAll = new javax.swing.JMenuItem();
        jM_edit = new javax.swing.JMenu();
        jMI_editColors = new javax.swing.JMenuItem();
        jMI_languageSub = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("yate");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(800, 600));

        jP_Menu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jB_newFile.setText("Neue Datei");
        jP_Menu.add(jB_newFile);

        jB_open.setText("Datei öffnen");
        jP_Menu.add(jB_open);

        jB_save.setText("Datei speichern");
        jP_Menu.add(jB_save);

        jB_saveAll.setText("Alle Dateien speichern");
        jP_Menu.add(jB_saveAll);
        jP_Menu.add(jCB_font);

        jCB_fontSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jP_Menu.add(jCB_fontSize);

        getContentPane().add(jP_Menu, java.awt.BorderLayout.PAGE_START);

        jP_Side.setLayout(new javax.swing.BoxLayout(jP_Side, javax.swing.BoxLayout.LINE_AXIS));

        jP_Pmv.setLayout(new javax.swing.BoxLayout(jP_Pmv, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(jP_Pmv);

        jP_Side.add(jScrollPane1);

        getContentPane().add(jP_Side, java.awt.BorderLayout.LINE_START);

        jP_Center.setLayout(new java.awt.BorderLayout());

        jTP_tabed.setMinimumSize(new java.awt.Dimension(500, 500));
        jP_Center.add(jTP_tabed, java.awt.BorderLayout.CENTER);

        jP_searchContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jP_search.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Suchen:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        jP_search.add(jLabel1, gridBagConstraints);

        jTF_search.setMaximumSize(new java.awt.Dimension(70, 20));
        jTF_search.setMinimumSize(new java.awt.Dimension(70, 20));
        jTF_search.setPreferredSize(new java.awt.Dimension(70, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        jP_search.add(jTF_search, gridBagConstraints);

        jLabel2.setText("Ersetzen:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        jP_search.add(jLabel2, gridBagConstraints);

        jTF_replace.setMaximumSize(new java.awt.Dimension(70, 20));
        jTF_replace.setMinimumSize(new java.awt.Dimension(70, 20));
        jTF_replace.setPreferredSize(new java.awt.Dimension(70, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        jP_search.add(jTF_replace, gridBagConstraints);

        jB_next.setText("Nächstes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        jP_search.add(jB_next, gridBagConstraints);

        jB_previous.setText("Vorheriges");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        jP_search.add(jB_previous, gridBagConstraints);

        jB_replace.setText("Ersetzen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        jP_search.add(jB_replace, gridBagConstraints);

        jB_replaceAll.setText("Alle ersetzen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        jP_search.add(jB_replaceAll, gridBagConstraints);

        jbCB_regex.setText("regex");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        jP_search.add(jbCB_regex, gridBagConstraints);

        jP_searchContainer.add(jP_search);

        jP_Center.add(jP_searchContainer, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jP_Center, java.awt.BorderLayout.CENTER);

        jM_file.setText("Datei");

        jMI_new.setText("Neue Datei");
        jM_file.add(jMI_new);

        jMI_open.setText("Datei öffnen");
        jM_file.add(jMI_open);

        jMI_save.setText("Datei speichern");
        jM_file.add(jMI_save);

        jMI_saveAll.setText("Alle Dateien speichern");
        jM_file.add(jMI_saveAll);

        jMB_menuBar.add(jM_file);

        jM_edit.setText("Bearbeiten");

        jMI_editColors.setText("Farben bearbeiten");
        jM_edit.add(jMI_editColors);

        jMI_languageSub.setText("Sprachen");
        jM_edit.add(jMI_languageSub);

        jMB_menuBar.add(jM_edit);

        setJMenuBar(jMB_menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_newFile;
    private javax.swing.JButton jB_next;
    private javax.swing.JButton jB_open;
    private javax.swing.JButton jB_previous;
    private javax.swing.JButton jB_replace;
    private javax.swing.JButton jB_replaceAll;
    private javax.swing.JButton jB_save;
    private javax.swing.JButton jB_saveAll;
    private javax.swing.JComboBox jCB_font;
    private javax.swing.JComboBox jCB_fontSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMB_menuBar;
    private javax.swing.JMenuItem jMI_editColors;
    private javax.swing.JMenu jMI_languageSub;
    private javax.swing.JMenuItem jMI_new;
    private javax.swing.JMenuItem jMI_open;
    private javax.swing.JMenuItem jMI_save;
    private javax.swing.JMenuItem jMI_saveAll;
    private javax.swing.JMenu jM_edit;
    private javax.swing.JMenu jM_file;
    private javax.swing.JPanel jP_Center;
    private javax.swing.JPanel jP_Menu;
    private javax.swing.JPanel jP_Pmv;
    private javax.swing.JPanel jP_Side;
    private javax.swing.JPanel jP_search;
    private javax.swing.JPanel jP_searchContainer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_replace;
    private javax.swing.JTextField jTF_search;
    private javax.swing.JTabbedPane jTP_tabed;
    private javax.swing.JCheckBox jbCB_regex;
    // End of variables declaration//GEN-END:variables

}
