package yate.view;

import java.util.HashMap;
import javax.swing.JComponent;

/**
 *
 * @author Laurin
 */
public class ProjectMenuView extends javax.swing.JPanel implements View{
    private HashMap<String,JComponent> components;

    /**
     * Creates new form SideMenu
     */
    public ProjectMenuView() {
        initComponents();
        components = new HashMap<>();
        addComponentsToHashMap();
    }
    
    private void addComponentsToHashMap()
    {
        components.put("jButton1", jButton1);
        components.put("jButton2", jButton2);
        components.put("jList1", jList1);
        components.put("jPanel1", jPanel1);
        components.put("jScrollPane1", jScrollPane1);
    }
    
    @Override
    public JComponent getComponent(String Name) {
        return components.get(Name);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setText("+");
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jPanel1.add(jButton1);

        jButton2.setText("-");
        jButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton2.setMaximumSize(new java.awt.Dimension(15, 20));
        jButton2.setMinimumSize(new java.awt.Dimension(15, 20));
        jButton2.setPreferredSize(new java.awt.Dimension(15, 20));
        jPanel1.add(jButton2);

        add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
